export const initialPlannerData = [
  {
    id: 0,
    priority: "High",
    status: "open",
    name: "Develop login page",
    labels: "feature",
    dueDate: "2024-12-01",
    created: "2024-11-01",
    assignee: "Amit",
    details:
      "You will see details of the task over here. There are a lot of things we need to take care of. We need to focus on accessibility too.",
    comments: [
      "Will have to start working on it from this week.",
      "There are few changes, we need to focus on this first.",
      "Working on the changes, will notify you tomorrow",
    ],
  },
  {
    id: 1,
    priority: "Medium",
    status: "inProgress",
    name: "Fix button alignment bug",
    labels: "bug",
    dueDate: "2024-12-05",
    created: "2024-10-10",
    assignee: "Priya",
    details:
      "This bug affects the layout on mobile devices. Ensure alignment fixes are compatible across screen sizes.",
    comments: [
      "Found the root cause of the alignment issue.",
      "Testing on different devices to confirm it's fixed.",
      "Almost done; need a few tweaks for better spacing.",
    ],
  },
  {
    id: 2,
    priority: "Low",
    status: "open",
    name: "Write API documentation",
    labels: "feature",
    dueDate: "2024-11-15",
    created: "2024-09-20",
    assignee: "Ravi",
    details:
      "Detail each API endpoint and expected responses. Use examples for clarity and ensure it covers edge cases.",
    comments: [
      "Started drafting the endpoint descriptions.",
      "Added examples for the first few endpoints.",
      "Reviewing edge cases to include in the documentation.",
    ],
  },
  {
    id: 3,
    priority: "High",
    status: "closed",
    name: "Integrate payment gateway",
    labels: "feature",
    dueDate: "2024-12-12",
    created: "2024-08-25",
    assignee: "Amit",
    details:
      "Integrate Stripe as the payment gateway. Ensure proper error handling and support for multiple currencies.",
    comments: [
      "Stripe integration is mostly complete.",
      "Testing for multiple currency support.",
      "Added error handling for payment failures.",
    ],
  },
  {
    id: 4,
    priority: "Low",
    status: "open",
    name: "Update README file",
    labels: "documentation",
    dueDate: "2024-12-10",
    created: "2024-07-30",
    assignee: "Priya",
    details:
      "Update README to reflect recent changes. Include installation instructions and major feature descriptions.",
    comments: [
      "Added initial setup instructions.",
      "Updated feature list in the README.",
      "Clarifying installation steps based on feedback.",
    ],
  },
  {
    id: 5,
    priority: "High",
    status: "open",
    name: "Design dashboard UI",
    labels: "feature",
    dueDate: "2024-11-25",
    created: "2024-06-22",
    assignee: "Ravi",
    details:
      "Design the user dashboard with responsiveness in mind. Include analytics and user activity overview sections.",
    comments: [
      "Started with wireframes for the dashboard.",
      "Focusing on responsiveness for various screen sizes.",
      "Incorporated analytics section as planned.",
    ],
  },
  {
    id: 6,
    priority: "Medium",
    status: "closed",
    name: "Set up CI/CD pipeline",
    labels: "infrastructure",
    dueDate: "2024-12-15",
    created: "2024-08-05",
    assignee: "Ankit",
    details:
      "Implement CI/CD pipeline with GitHub Actions. Ensure automated tests run and deployments to staging are smooth.",
    comments: [
      "Configured GitHub Actions for automated tests.",
      "Deployment to staging environment is working.",
      "Debugging minor issues with test automation.",
    ],
  },
  {
    id: 7,
    priority: "Low",
    status: "inProgress",
    name: "Refactor homepage code",
    labels: "feature",
    dueDate: "2024-11-18",
    created: "2024-09-10",
    assignee: "Priya",
    details:
      "Refactor homepage for better performance. Focus on reducing render times and optimizing image loading.",
    comments: [
      "Identified parts of the code for optimization.",
      "Working on reducing the render times.",
      "Optimizing image loading strategy for faster load times.",
    ],
  },
  {
    id: 8,
    priority: "High",
    status: "open",
    name: "Build user authentication",
    labels: "feature",
    dueDate: "2024-12-20",
    created: "2024-10-01",
    assignee: "Ravi",
    details:
      "Implement secure user authentication with password encryption. Allow login via email and social accounts.",
    comments: [
      "Implemented password encryption for secure login.",
      "Testing social account login integration.",
      "Added basic login and signup forms for testing.",
    ],
  },
  {
    id: 9,
    priority: "Medium",
    status: "closed",
    name: "Fix mobile layout issue",
    labels: "bug",
    dueDate: "2024-12-25",
    created: "2024-07-15",
    assignee: "Amit",
    details:
      "Fix issues with layout shifting on smaller screens. Verify that padding and margins are responsive.",
    comments: [
      "Adjusted margins to fix shifting issues.",
      "Tested responsiveness on various screen sizes.",
      "Finalized adjustments; layout now stable on mobile.",
    ],
  },
  {
    id: 10,
    priority: "High",
    status: "closed",
    name: "Implement search functionality",
    labels: "feature",
    dueDate: "2024-11-30",
    created: "2024-09-05",
    assignee: "Priya",
    details:
      "Implement search with filters by date and priority. Optimize for fast performance on large data sets.",
    comments: [
      "Set up basic search functionality.",
      "Added filters for date and priority.",
      "Working on optimizing for large data sets.",
    ],
  },
  {
    id: 11,
    priority: "High",
    status: "inProgress",
    name: "Update project dependencies",
    labels: "maintenance",
    dueDate: "2024-11-10",
    created: "2024-08-20",
    assignee: "Ankit",
    details:
      "Update all project dependencies to their latest versions. Test compatibility and resolve breaking changes.",
    comments: [
      "Started with core dependency updates.",
      "Testing for compatibility issues after updates.",
      "Resolved major breaking changes in dependencies.",
    ],
  },
  {
    id: 12,
    priority: "High",
    status: "inProgress",
    name: "Implement file upload feature",
    labels: "feature",
    dueDate: "2024-12-05",
    created: "2024-10-12",
    assignee: "Ravi",
    details:
      "Build a file upload feature supporting various formats. Ensure large files are uploaded with error handling.",
    comments: [
      "Basic file upload functionality is in place.",
      "Testing support for different file formats.",
      "Handling errors for large file uploads.",
    ],
  },
  {
    id: 13,
    priority: "Medium",
    status: "open",
    name: "Fix database connection issue",
    labels: "bug",
    dueDate: "2024-12-10",
    created: "2024-09-30",
    assignee: "Amit",
    details:
      "Resolve connection issues with the database. Check for connection pooling and optimize connection limits.",
    comments: [
      "Investigating connection pooling settings.",
      "Adjusted connection limits for better stability.",
      "Monitoring database for connection improvements.",
    ],
  },
  {
    id: 14,
    priority: "Low",
    status: "closed",
    name: "Optimize CSS for mobile",
    labels: "performance",
    dueDate: "2024-11-28",
    created: "2024-06-10",
    assignee: "Priya",
    details:
      "Optimize CSS to improve mobile performance. Minify CSS files and reduce unused styles for faster load times.",
    comments: [
      "Started removing unused styles.",
      "Minified CSS files to reduce load times.",
      "Testing CSS performance on mobile devices.",
    ],
  },
];
